### ISSUE TITLE
Support Adafruit Feather 32u4 FONA

### ISSUE THREAD

**Issue by opencsi-leon** [CasaJasmina/TelegramBot-Library#11]
Your library is fantastic!
I want to use it to Adafruit Feather 32u4 FONA with GPRS connection.
https://www.adafruit.com/product/3027

Can you help me?

Thanks
Leonardo

**Comment by gibix** [comment]
Thanks @opencsi-leon for your comment. 
I never tried that board, but looking at the docs I don't think that is currently possible to be supported. There are no library to establish a stable tcp/ip connection with FONA board.
At now we prefer to focus our efforts on features and performances.
