### ISSUE TITLE
getUpdates Api call should have an offset of last_message_recieved + 1

### ISSUE THREAD

**Issue by witnessmenow** [CasaJasmina/TelegramBot-Library#13]
When calling the Telegram API for getUpdates, the value of the offset parameter should be the Id of the last received message + 1

From [here](https://core.telegram.org/bots/api#getupdates)

> Identifier of the first update to be returned. Must be greater by one than the highest among the identifiers of previously received updates.

Problem line is here in [TelegramBot.cpp](https://github.com/CasaJasmina/TelegramBot-Library/blob/master/src/TelegramBot.cpp#L31)

This causes the issue described by @didgerihorn in the comments #8 where the last message in an echo bot is repeated over and over again. Telegram does not consider a message confirmed til getUpdates is called with a higher offset.

I can't really provide a pull request as I do not have a board to test

**Comment by PascalGuenther** [comment]
Updating the Id seems to work, otherwise, every call of getUpdates would receive the same massage all over again. The strange thing is  that you have to call getUpdates several hundret times before a message is received again

**Comment by witnessmenow** [comment]
@didgerihorn , I'm not sure what you mean about needing to call in hundred times before new messages are received, is this after updating the offset to be + 1?

**Comment by PascalGuenther** [comment]
Yey indeed, because this library is based on polling you run getUpdates about 20 times per minute. the repeated messeges occur without any regularity, from 6 minutes up to several hours till a messege is received again. I am running the library on ESP which is not supported offically

**Comment by witnessmenow** [comment]
Hmm, thats wierd. I have done a good bit of Telegram bot programing (in Node JS mostly) and have ran into some weird issues now and again with Telegram itself

A good thing to do to rule out the library causing the issues is to hit the API call directly to see are you getting any messages through that way.

Maybe try another bot token to see is that having the same problems

**Comment by PascalGuenther** [comment]
I am currently not working on this or any other telegram-related project, thats why I haven't opened an issue

**Comment by witnessmenow** [comment]
If this is changed a code change on the getUpdates parser will need to be made

https://github.com/CasaJasmina/TelegramBot-Library/blob/master/src/TelegramBot.cpp#L45

It references the second element in the array, presumably because the offset being passed in was one behind. If the offset is updated the new message will be the first element in the array

**Comment by lorenzoromagnoli** [comment]
@witnessmenow can you please provide a PR?

**Comment by witnessmenow** [comment]
Hi @lorenzoromagnoli 

I can for sure, but I do not have a compatible board. If i provide a PR can someone else test it? The change should be straightforward enough.
