### ISSUE TITLE
It should work in groups

### ISSUE THREAD

**Issue by lukks22** [CasaJasmina/TelegramBot-Library#16]
Unluckily, when I try to send a message in group, it doesn't work

**Comment by tommasoltrz** [comment]
When the bot is included in a group it will be, by default, in privacy mode. Which means that it will receive only messages starting with "/", the so called commands.  You can disable this behaviour by talking with the BotFather

**Comment by lukks22** [comment]
Yes, I know this, in fact the MKR receives the messages. The problem is when I try to SEND messages in groups. I tried lots of different IDs (with "-100", without it...) but no one of them works..
