### ISSUE TITLE
TelegramBot on ESP-01

### ISSUE THREAD

**Issue by pvanessen** [CasaJasmina/TelegramBot-Library#19]
Hi,

i used this library yesterday, and the Echobot example worked fine for about 10 mins. 
Then, this behavior started. 

> ....
> Connected to Phillips WLAN-Netzwerk
> IP address: 192.168.1.10
> MDNS responder started
> Bot started.
> Free heap: 36032
> GET Update Messages 
> :ref 1
> ssl/tls1.c:545 malloc 6864, left 28368
> please start sntp first !
> State:	sending Client Hello (1)
> :wr
> :sent 52
> :ww
> :rn 1460
> :rd 5, 1460, 0
> :rdi 1460, 5
> :rd 74, 1460, 5
> :rdi 1455, 74
> State:	receiving Server Hello (2)
> :rd 5, 1460, 79
> :rdi 1381, 5
> :rd:rch 1460, 1460
> :rch 2920, 1460
> :rch 4380, 481
>  1376, 1460, 84
> :rdi 1376, 1376
> :c 1376, 1460, 4861
> :rd 3392, 3401, 0
> :rdi 1460, 1460
> :c 1460, 1460, 3401
> :rdi 1460, 1460
> :c 1460, 1460, 1941
> :rdi 481, 472
> State:	receiving Certificate (11)
> crypto/bigint.c:1072 realloc 1032, left 23936
> crypto/bigint.c:1072 realloc 1032, left 20336
> crypto/bigint.c:1072 realloc 1032, left 16896
> crypto/bigint.c:1072 realloc 1032, left 12936
> :rd 5, 481, 472
> :rdi 9, 5
> :rd 4, 481, 477
> :rdi 4, 4
> :c0 4, 481
> State:	receiving Server Hello Done (14)
> crypto/bigint.c:1072 realloc 1024, left 9544
> State:	sending Client Key Exchange (16)
> :wr
> :sent 267
> :ww
> :wr
> :sent 6
> :ww
> State:	sending Finished (16)
> :wr
> :sent 69
> :rn 75
> :ww
> :rd 5, 75, 0
> :rdi 75, 5
> :rd 1, 75, 5
> :rdi 70, 1
> :rd 5, 75, 6
> :rdi 69, 5
> :rd 64, 75, 11
> :rdi 64, 64
> :c0 64, 75
> State:	receiving Finished (16)
> :wr
> :sent 117
> :ww
> :wr
> :sent 53
> :ww
> :rn 1061
> :rch 1061, 53
> :rcl
> :abort
> :rd 5, 1114, 0
> :rdi 1061, 5
> :rd 1056, 1114, 5
> :rdi 1056, 1056
> :c 1056, 1061, 1114
> :wcs ra 1011:rd 5, 53, 0
> :rdi 53, 5
> :rd 48, 53, 5
> :rdi 48, 48
> :c0 48, 53
> Alert: close notify
> Sent Update request messages up to : 0
> {"update_id":958751008,
> "message":{"message_id":30,"from":{"id":357633951,"first_name":"Phillip","last_name":"van Essen","username":"pvanessen"},"chat":{"id":357633951,"first_name":"Phillip","last_name":"van Essen","username":"pvanessen","type":"private"},"date":1489293582,"text":"TEST"}},
> 
> 
> Soft WDT reset
> 
> ctx: cont 
> sp: 3fff12f0 end: 3fff1610 offset: 01b0
> 
> >>>stack>>>
> 3fff14a0:  3fff51e9 00000122 3fff1514 40205f1f  
> 3fff14b0:  3fff0508 000001d8 3fff0508 4010054f  
> 3fff14c0:  00000033 3fff02f4 3fff2e04 401008d9  
> 3fff14d0:  3ffe920b 3fff02f4 3fff1508 40205e74  
> 3fff14e0:  00000095 3fff02f4 000000a2 402051ae  
> 3fff14f0:  00000000 00000000 00000000 00000000  
> 3fff1500:  0000009e 00000000 3fff2e0c 0000000f  
> 3fff1510:  0000000d 3fff5154 0000012f 00000122  
> 3fff1520:  3fff02ac 00000001 3fff0330 00000122  
> 3fff1530:  00000000 00000004 3fff052c 40205c38  
> 3fff1540:  3fff052c 3fff02ac 00000001 00000002  
> 3fff1550:  3fff052c 3fff02ac 00000001 402057ce  
> 3fff1560:  00000000 00000000 00000000 00000000  
> 3fff1570:  00000000 00000000 00000000 00000000  
> 3fff1580:  00000000 3fff9574 000002bf 000002bc  
> 3fff1590:  3fff33b4 0000004f 00000044 40205f51  
> 3fff15a0:  3fff02f4 00000168 00000167 0000029f  
> 3fff15b0:  3fffdad0 00000000 3fff02a8 3fff05e8  
> 3fff15c0:  3fffdad0 00000000 3fff02a8 40202232  
> 3fff15d0:  3fff3314 0000000f 00000001 00000000  
> 3fff15e0:  00000000 00000000 feefeffe 40205b01  
> 3fff15f0:  3fffdad0 00000000 3fff05e0 4020642c  
> 3fff1600:  feefeffe feefeffe 3fff05f0 40100970  
> <<<stack<<<
> 
>  ets Jan  8 2013,rst cause:1, boot mode:(3,7)

My code:

```
#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266WebServer.h>
#include <ESP8266mDNS.h>
#include <ESP8266TelegramBOT.h>


const char* ssid = "mySSID";
const char* password = "mypass";
const int sleepTimeS = 30;

// Initialize Telegram BOT
#define BOTtoken "myToken"  //token of TestBOT
#define BOTname "mybotname"
#define BOTusername "mybotusernamet"
TelegramBOT bot(BOTtoken, BOTname, BOTusername);

int Bot_mtbs = 1000; //mean time between scan messages
long Bot_lasttime;   //last time messages' scan has been done

/********************************************
 * EchoMessages - function to Echo messages *
 ********************************************/
void Bot_EchoMessages() {

  for (int i = 1; i < bot.message[0][0].toInt() + 1; i++)      {
    bot.sendMessage(bot.message[i][4], bot.message[i][5], "");
  }
  bot.message[0][0] = "";   // All messages have been replied - reset new messages
}


void setup(void){
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  Serial.println("");

  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  if (MDNS.begin("esp8266")) {
    Serial.println("MDNS responder started");
  }
 
  bot.begin();
  Serial.println("Bot started.");
}



void loop(void){
  
  if (millis() > Bot_lasttime + Bot_mtbs)  {
    Serial.println("Free heap: " + String(ESP.getFreeHeap(),DEC));
    bot.getUpdates(bot.message[0][1]);   // launch API GetUpdates up to xxx message
    Bot_EchoMessages();   // reply to message with Echo
    Bot_lasttime = millis();
  }
}
```

**Comment by tommasoltrz** [comment]
Hi,
it seems like you are using a different library, not this one.
You are probably referring to https://github.com/Gianbacchio/ESP8266-TelegramBot .
