### ISSUE TITLE
Memory 

### ISSUE THREAD

**Issue by joern-schlingensiepen** [CasaJasmina/TelegramBot-Library#20]
Dear Tommaso,

thank you for fiddeling out the JSON serialization of the Keyboard and sharing this lib, it helped a lot.

I had an Issue on my ESP8266 it caused an exception (29), which is `storeprohibitedcause`.
I changed line 13 in TelegramKeyboard.cpp to:
    `button* first = new button();`

since `first->next = NULL` is not allowed while `first `is not initialised / allocated.

Best Regards

Jörn

**Comment by tommasoltrz** [comment]
Thanks for the hint, we updated the library and fixed it !
