### ISSUE TITLE
Bot seems to be stucked after first message

### ISSUE THREAD

**Issue by valluzzi** [CasaJasmina/TelegramBot-Library#24]
I tried EchoBot.ino with MKR1000 and after the first message replied I have non more response from the EchoBot. I thinked the problem was in getUpdates but If you comment line 62 (bot.sendMessage(m.chat_id, m.text);) all goes pretty well ... despite the fact your bot doesn't speak.

So I thinked the problem was in sendMessage and I tried randomly to comment lines in postMessage function.... and I don't know why, but removing this line (line 136 in TelegramBot.cpp)
client->println("Connection: close"); 
the bot starts working as expected.

**Comment by Markhaus** [comment]
Hello,
I confirm that removing line 136 in TelegramBot.cpp: client->println("Connection: close");
Solved my issue. Thank you!
FYI My bot was connecting properly and responding but was very unstable and getting stucked very often.
After commenting the line 136 in the TelegramBot.cpp file the script is now stable and responding fairly quick (3secs).
Arduino version 1.8.10
Arduinojson version 5.13.4
TelegramBot version 1.2.5
Hardware MKR1000
