### ISSUE TITLE
NodeMCU v3 resets on message m = bot.getUpdates();

### ISSUE THREAD

**Issue by konig87nikkinakki** [CasaJasmina/TelegramBot-Library#34]
Hi,
i'm using Arduino Ide to compile NodeMCU with your library.
if i use ESP8266 v2.3.0 it works good (Settings --> Gestore Schede)
if i upgrade to the last version v2.6.3 it crashes and reboot when i call 
`message m = bot.getUpdates();`

i can continue using v2.3.0 but i'm afraid in the future it will be impossible to downgrade to!
i think it's a Setting problem, what kind of settings do you use?
thanks

with v2.3.0 i m using:
Shield: nodeMCU 1.0 ESP 12E module
CPU freq: 80MHz
Flash size: 4M (3M SPIFFS)
Upload Speed: 115200.

With v2.6.3 version there are a loooot of more settings to do, what are yours?

**Comment by kilbasovich** [comment]
accept this method in your code 
    client.setInsecure();

**Comment by konig87nikkinakki** [comment]
> accept this method in your code
> client.setInsecure();

Hi,
sorry for my ignorance.
i tried to put client.setInsecure(); in Setup function but it doesnt compile and write me:
```
exit status 1
'client' was not declared in this scope
```
I m using
ArduinoJson Library by Benoit Blanchon v5.13.1, TelegramBot by CasaJasmina v1.2.5 , ESP8266 shield v2.6.3

And here's my code (taken from your Example EchoBot8266)

```
#include "arduino_secrets.h"
#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>
#include <TelegramBot.h>

// Initialize Wifi connection to the router
const char* ssid  = SECRET_SSID;
const char* password = SECRET_PASS;


// Initialize Telegram BOT
const char BotToken[] = SECRET_BOT_TOKEN;

WiFiClientSecure net_ssl;
TelegramBot bot (BotToken, net_ssl);
void setup() {

  Serial.begin(9600);
  while (!Serial); // Wait for the Serial monitor to be opened

  // attempt to connect to Wifi network:
  Serial.print("Connecting Wifi: ");
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");


  bot.begin();
client.setInsecure();
}

void loop() {
 
    message m = bot.getUpdates(); // Read new messages
    if ( m.chat_id != 0 ){ // Checks if there are some updates
      Serial.println(m.text);
      bot.sendMessage(m.chat_id, m.text);  // Reply to the same chat with the same text
    } else {
      Serial.println("no new message");
    }

}
```

Where am i wrong? of course i filled arduino_secrets.h with my WIFI data and my TelegramBot token.
Thank you again, and sorry for my ignorance.

**Comment by kilbasovich** [comment]
`WiFiClientSecure **client**;
TelegramBot bot (BotToken, **client**);
void setup() {`

**Comment by kilbasovich** [comment]
```
WiFiClientSecure client;
TelegramBot bot (BotToken, client);
void setup() {
```

**Comment by sganzerla** [comment]
@konig87nikkinakki your error is name client SSL

```
// client.setInsecure();
net_ssl..setInsecure();
```

Change like this code and run ok.
Can close issue, please.

```
include "arduino_secrets.h"
#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>
#include <TelegramBot.h>

// Initialize Wifi connection to the router
const char* ssid  = SECRET_SSID;
const char* password = SECRET_PASS;


// Initialize Telegram BOT
const char BotToken[] = SECRET_BOT_TOKEN;

WiFiClientSecure net_ssl;
TelegramBot bot (BotToken, net_ssl);
void setup() {

  Serial.begin(9600);
  while (!Serial); // Wait for the Serial monitor to be opened

  // attempt to connect to Wifi network:
  Serial.print("Connecting Wifi: ");
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");


  bot.begin();
// client.setInsecure();
net_ssl..setInsecure();
}

void loop() {
 
    message m = bot.getUpdates(); // Read new messages
    if ( m.chat_id != 0 ){ // Checks if there are some updates
      Serial.println(m.text);
      bot.sendMessage(m.chat_id, m.text);  // Reply to the same chat with the same text
    } else {
      Serial.println("no new message");
    }

}
```

**Comment by kilbasovich** [comment]
> ```
> #include <ESP8266WiFi.h>
> #include <WiFiClientSecure.h>
> #include <TelegramBot.h>
> 
> // Initialize Wifi connection to the router
> const char* ssid  = SECRET_SSID;
> const char* password = SECRET_PASS;
> 
> 
> // Initialize Telegram BOT
> const char BotToken[] = SECRET_BOT_TOKEN;
> 
> WiFiClientSecure client;
> TelegramBot bot (BotToken, client);
> void setup() {
> 
>   Serial.begin(9600);
>   while (!Serial); // Wait for the Serial monitor to be opened
> 
>   // attempt to connect to Wifi network:
>   Serial.print("Connecting Wifi: ");
>   WiFi.begin(ssid, password);
>   while (WiFi.status() != WL_CONNECTED) {
>     delay(500);
>     Serial.print(".");
>   }
>   Serial.println("");
>   Serial.println("WiFi connected");
> 
> client.setInsecure();
>   bot.begin();
> }
> 
> void loop() {
>  
>     message m = bot.getUpdates(); // Read new messages
>     if ( m.chat_id != 0 ){ // Checks if there are some updates
>       Serial.println(m.text);
>       bot.sendMessage(m.chat_id, m.text);  // Reply to the same chat with the same text
>     } else {
>       Serial.println("no new message");
>     }
> 
> }
> ```

**Comment by konig87nikkinakki** [comment]
ok, it works, even if i dont have time enought to test it for several hours to understand if it's stable script :-)
THANK YOU SO MUCH, please update library examples with new scripts, otherwise not-expert like me go crazy 👍
