### ISSUE TITLE
name and username should not be parameters for the constructor

### ISSUE THREAD

**Issue by witnessmenow** [CasaJasmina/TelegramBot-Library#6]
As the only thing used by Telegram is the bot token that should be the only thing related to the bot passed into the constructor. If users need to have access to the bot name or username the getMe api call could be implemented. It would be more accurate to do this as it is exactly tied to the bot token

I will try contribute to the library if you are interested. I know telegram fairly well but am brand new to arduino and haven't programmed in cpp since the one semester I did in college a long time ago!

**Comment by gibix** [comment]
Thanks, there is a branch and a open PR #10 if you want to contribute.
